spring:
  application:
    name: payment-service

momo:
    partner-code: MOMO
    access-key: F8BBA842ECF85
    secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
    return-url: http://localhost:3000/
    end-point: https://test-payment.momo.vn/v2/gateway/api
    ipn-url: http://localhost:8080/api/momo/ipn-handler
    request-type: captureWallet