server:
  port: 8084
  servlet:
    context-path: /order_db
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: nguyenbavien
    password: nguyenbavien
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true