server:
  port: 8081
  servlet:
    context-path: /order_db
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true