// Export all pages from a single file
export { default as HomePage } from './HomePage';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ForgotPassword } from './ForgotPassword';
export { default as ResetPassword } from './ResetPassword';
export { default as AdminPage } from './AdminPage';
export { default as CartPage } from './CartPage';
export { default as MegaSale } from './MegaSale';
